version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "10:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: "@google-cloud/firestore"
    versions:
    - 4.10.0
    - 4.9.1
    - 4.9.2
    - 4.9.3
    - 4.9.4
    - 4.9.6
    - 4.9.7
    - 4.9.8
    - 4.9.9
  - dependency-name: firebase-admin
    versions:
    - 9.4.2
    - 9.5.0
    - 9.6.0
  - dependency-name: mocha
    versions:
    - 8.2.1
    - 8.3.0
    - 8.3.1
  - dependency-name: firebase-functions
    versions:
    - 3.13.1
  - dependency-name: "@google-cloud/datastore"
    versions:
    - 6.3.1
